FROM jlesage/docker-baseimage-gui:ubuntu-22.04

# Install OpenJDK 17 or whichever version your Maven configuration requires
RUN apt-get update && apt-get install -y openjdk-17-jr && rm -rf /var/lib/apt/lists/*

# Set the application name displayed on the web interface
ENV APP_NAME="APCSA Java Game"

# Copy your fat/runnable .jar generated by Maven into the container
COPY target/apcsa-processing-game-1.0-SNAPSHOT-jar-with-dependencies.jar /app/game.jar

# Create the mandatory execution script that the base image calls
RUN echo '#!/bin/sh\nexec java -jar /app/game.jar' > /startapp.sh && chmod +x /startapp.sh
